USE reclamos_auto;

CREATE TABLE IF NOT EXISTS catalogos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo_catalogo VARCHAR(60) NOT NULL,
    codigo VARCHAR(120) NOT NULL,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT NULL,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    orden INT NOT NULL DEFAULT 0,
    es_default TINYINT(1) NOT NULL DEFAULT 0,
    pendiente_revision TINYINT(1) NOT NULL DEFAULT 0,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_catalogos_tipo_codigo (tipo_catalogo, codigo),
    INDEX ix_catalogos_tipo_activo_orden (tipo_catalogo, activo, orden)
);

INSERT INTO catalogos (tipo_catalogo, codigo, nombre, activo, orden, es_default, pendiente_revision)
VALUES
-- COMPANIAS
('COMPANIAS','SEGUROS_ATLANTIDA','SEGUROS ATLANTIDA',1,10,0,0),
('COMPANIAS','SEGUROS_CREFISA','SEGUROS CREFISA',1,20,0,0),
('COMPANIAS','MAPFRE','MAPFRE',1,30,0,0),
('COMPANIAS','MAPRE','MAPRE',1,31,0,0),
('COMPANIAS','SEGUROS_CONTINENTAL','SEGUROS CONTINENTAL',1,40,0,0),
('COMPANIAS','FICOHSA_SEGUROS','FICOHSA SEGUROS',1,50,0,0),
('COMPANIAS','SEGUROS_DAVIVIENDA','SEGUROS DAVIVIENDA',1,60,0,0),

-- RAMOS
('RAMOS','ACCIDENTES_PERSONALES','ACCIDENTES PERSONALES',1,10,0,0),
('RAMOS','AUTO','AUTO',1,20,0,0),
('RAMOS','MOTOS','MOTOS',1,30,0,0),
('RAMOS','VIDA','VIDA',1,40,0,0),
('RAMOS','MEDICO','MEDICO',1,50,0,0),
('RAMOS','INCENDIO','INCENDIO',1,60,0,0),
('RAMOS','MAQUINARIA','MAQUINARIA',1,70,0,0),
('RAMOS','MAQUINARIA_Y_EQUIPO','MAQUINARIA Y EQUIPO',1,80,0,0),
('RAMOS','VIDA2000','VIDA2000',1,90,0,0),

-- FORMAS DE PAGO
('FORMAS_PAGO','TRANSFERENCIA','TRANSFERENCIA',1,10,0,0),
('FORMAS_PAGO','CONTADO','CONTADO',1,20,1,0),
('FORMAS_PAGO','EXTRAFINANCIAMIENTO','EXTRAFINANCIAMIENTO',1,30,0,0),
('FORMAS_PAGO','DEBITO_AUTOMATICO','DEBITO AUTOMATICO',1,40,0,0),

-- EMISION / RENOVACION
('EMISION_RENOVACION','EMISION','EMISION',1,10,1,0),
('EMISION_RENOVACION','RENOVACION','RENOVACION',1,20,0,0),
('EMISION_RENOVACION','OTRAS','OTRAS',1,30,0,0),

-- MEDIOS
('MEDIOS','NOMBRAMIENTO','NOMBRAMIENTO',1,10,0,0),
('MEDIOS','REFERENCIA','REFERENCIA',1,20,0,0),
('MEDIOS','CONTACTO_PROPIO','CONTACTO PROPIO',1,30,1,0),

-- ENDOSATARIOS (bancos/financieras)
('ENDOSATARIOS','BANCO_ATLANTIDA','BANCO ATLANTIDA',1,10,0,0),
('ENDOSATARIOS','LEASING_ATLANTIDA','LEASING ATLANTIDA',1,20,0,0),
('ENDOSATARIOS','BANCO_OCCIDENTE','BANCO DE OCCIDENTE',1,30,0,0),
('ENDOSATARIOS','BANPAIS','BANPAIS',1,40,0,0),
('ENDOSATARIOS','BAC_CREDOMATIC','BAC CREDOMATIC',1,50,0,0),
('ENDOSATARIOS','FICOHSA_BANCO','BANCO FICOHSA',1,60,0,0),
('ENDOSATARIOS','DAVIVIENDA_BANCO','BANCO DAVIVIENDA',1,70,0,0),
('ENDOSATARIOS','BANRURAL_HN','BANRURAL HONDURAS',1,80,0,0),
('ENDOSATARIOS','BANCATLAN','BANCATLAN',1,90,0,0),
('ENDOSATARIOS','BCH','BANCO CENTRAL DE HONDURAS',1,100,0,0),
('ENDOSATARIOS','COFISA','COFISA',1,110,0,0),
('ENDOSATARIOS','CREDIQ','CREDIQ',1,120,0,0),
('ENDOSATARIOS','CREDISOL','CREDISOL',1,130,0,0),
('ENDOSATARIOS','FIDESA','FIDESA',1,140,0,0),
('ENDOSATARIOS','FUNDEA','FUNDEA',1,150,0,0),
('ENDOSATARIOS','OCREDE_HN','OCREDE HN',1,160,0,0),
('ENDOSATARIOS','LEASING_FICOHSA','LEASING FICOHSA',1,170,0,0),
('ENDOSATARIOS','LEASING_BAC','LEASING BAC',1,180,0,0),
('ENDOSATARIOS','LEASING_DAVIVIENDA','LEASING DAVIVIENDA',1,190,0,0),
('ENDOSATARIOS','FINANCIERA_CREDIMAS','FINANCIERA CREDIMAS',1,200,0,0),
('ENDOSATARIOS','FINANCIERA_EL_COMERCIO','FINANCIERA EL COMERCIO',1,210,0,0)
ON DUPLICATE KEY UPDATE
    nombre = VALUES(nombre),
    activo = VALUES(activo),
    orden = VALUES(orden),
    es_default = VALUES(es_default),
    pendiente_revision = VALUES(pendiente_revision);

-- Limpieza visual para UI (sin guiones bajos en nombre visible)
UPDATE catalogos
SET nombre = TRIM(REPLACE(REPLACE(REPLACE(nombre, '_', ' '), '  ', ' '), '  ', ' '))
WHERE tipo_catalogo IN ('COMPANIAS','RAMOS','FORMAS_PAGO','EMISION_RENOVACION','MEDIOS','ENDOSATARIOS');
