SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE app_settings;
TRUNCATE TABLE auditoria_logs;
TRUNCATE TABLE automatizacion_acciones;
TRUNCATE TABLE automatizacion_condiciones;
TRUNCATE TABLE automatizacion_logs;
TRUNCATE TABLE automatizaciones;
TRUNCATE TABLE carteraclientes;
TRUNCATE TABLE catalogos;
TRUNCATE TABLE cliente_telefonos;
TRUNCATE TABLE clientes;
TRUNCATE TABLE comisiones_detalle;
TRUNCATE TABLE comisiones_lotes;
TRUNCATE TABLE correo_reclamo_condiciones;
TRUNCATE TABLE correo_reclamo_patrones;
TRUNCATE TABLE correo_reclamo_plantilla_reglas;
TRUNCATE TABLE correo_reclamo_plantillas;
TRUNCATE TABLE cotizacion_archivos;
TRUNCATE TABLE cotizacion_comparativos;
TRUNCATE TABLE cotizacion_datos_extraidos;
TRUNCATE TABLE cotizacion_envios;
TRUNCATE TABLE cotizacion_mapeos_aseguradora;
TRUNCATE TABLE cotizacion_oportunidades;
TRUNCATE TABLE documentos;
TRUNCATE TABLE empresa_configuracion;
TRUNCATE TABLE gastos;
TRUNCATE TABLE notificaciones_internas;
TRUNCATE TABLE poliza_pagos;
TRUNCATE TABLE poliza_cuotas;
TRUNCATE TABLE polizas;
TRUNCATE TABLE reclamo_documentos;
TRUNCATE TABLE reclamo_requisitos;
TRUNCATE TABLE reclamos_whatsapp;
TRUNCATE TABLE recordatorios;
TRUNCATE TABLE roles;
TRUNCATE TABLE taller_aseguradoras;
TRUNCATE TABLE taller_ramos;
TRUNCATE TABLE talleres;
TRUNCATE TABLE talleres_detectados;
TRUNCATE TABLE users;
TRUNCATE TABLE vehiculo_cambios;
TRUNCATE TABLE vehiculo_historial;
TRUNCATE TABLE vehiculos;
TRUNCATE TABLE whatsapp_envios_log;

SET FOREIGN_KEY_CHECKS = 1;
