INSERT IGNORE INTO Roles (Name) VALUES ('ADMIN'), ('GERENTE'), ('EJECUTIVO'), ('SOLO_LECTURA');

UPDATE Users SET RoleId = (SELECT Id FROM Roles WHERE Name = 'ADMIN' LIMIT 1)
WHERE RoleId IN (SELECT Id FROM Roles WHERE Name = 'Admin');

UPDATE Users SET RoleId = (SELECT Id FROM Roles WHERE Name = 'EJECUTIVO' LIMIT 1)
WHERE RoleId IN (SELECT Id FROM Roles WHERE Name = 'User');

DELETE FROM Roles WHERE Name IN ('Admin', 'User');

ALTER TABLE Users
    ADD COLUMN IF NOT EXISTS FailedLoginAttempts INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS LockoutUntil DATETIME NULL,
    ADD COLUMN IF NOT EXISTS LastPasswordChange DATETIME NULL;
